export const pagesRoutes = [
  ["v-8daa1a0e","/",{"t":"主页","i":"home"},["/index.html","/README.md"]],
  ["v-94c65946","/related/",{"t":"奇奇怪怪"},["/related/index.html","/related/README.md"]],
  ["v-2d0a870d","/en/",{"t":"home","i":"home"},["/en/index.html","/en/README.md"]],
  ["v-77220242","/board/",{"t":"留言板"},["/board/index.html","/board/README.md"]],
  ["v-5c6c891c","/behind/",{"t":"幕后故事","i":"creative"},["/behind/index.html","/behind/README.md"]],
  ["v-2d0ace41","/xm/",{"t":"1.小末花概述"},["/xm/index.html","/xm/README.md"]],
  ["v-2053069e","/xm/description.html",{"t":"2.形态特征"},["/xm/description","/xm/description.md"]],
  ["v-54297892","/xm/method.html",{"t":"3.生活习性及养殖方法"},["/xm/method","/xm/method.md"]],
  ["v-60a3448b","/xm/process.html",{"t":"4.进化历程"},["/xm/process","/xm/process.md"]],
  ["v-35859f09","/xm/value.html",{"t":"5.应用价值"},["/xm/value","/xm/value.md"]],
  ["v-299412f0","/en/behind/",{"t":"Behind the cover","i":"creative"},["/en/behind/index.html","/en/behind/README.md"]],
  ["v-7c1bd1ad","/en/xm/",{"t":"Summary"},["/en/xm/index.html","/en/xm/README.md"]],
  ["v-32a7b20a","/en/xm/description.html",{"t":"2.形态特征"},["/en/xm/description","/en/xm/description.md"]],
  ["v-761c24cb","/en/xm/method.html",{"t":"3.生活习性及养殖方法"},["/en/xm/method","/en/xm/method.md"]],
  ["v-72e2f412","/en/xm/process.html",{"t":"4.进化历程"},["/en/xm/process","/en/xm/process.md"]],
  ["v-21ea4b75","/en/xm/value.html",{"t":"5.应用价值"},["/en/xm/value","/en/xm/value.md"]],
  ["v-00011371","/en/related/",{"t":"Something Strange"},["/en/related/index.html","/en/related/README.md"]],
  ["v-3706649a","/404.html",{"t":""},["/404"]],
]
